#define animLynxIdleLt_Width   (3)
#define animLynxIdleLt_Height  (2)

const char animLynxIdleLt[3 * 2] PROGMEM=
{
    0,  1,  2,
    3,  4,  5
};

#define animLynxIdleRt_Width   (3)
#define animLynxIdleRt_Height  (2)

const char animLynxIdleRt[3 * 2] PROGMEM=
{
    6,  7,  8,
    9, 10, 11
};

#define animLynxRunLt_Width   (3)
#define animLynxRunLt_Height  (10)

const char animLynxRunLt[3 * 10] PROGMEM=
{
   12,  1,  2,
   13, 14, 15,
   16,  1, 17,
   18, 19, 20,
    0, 21, 22,
   23, 24, 25,
    0, 26, 27,
   28, 29, 30,
    0,  1, 31,
   32, 33, 34
};

#define animLynxRunRt_Width   (3)
#define animLynxRunRt_Height  (10)

const char animLynxRunRt[3 * 10] PROGMEM=
{
    6,  7, 35,
   36, 37, 38,
   39,  7, 40,
   41, 42, 43,
   44, 45,  8,
   46, 47, 48,
   49, 50,  8,
   51, 52, 53,
   54,  7,  8,
   55, 56, 57
};

#define animDFlyLt_Width   (2)
#define animDFlyLt_Height  (6)

const char animDFlyLt[2 * 6] PROGMEM=
{
   58, 59,
   60, 61,
   62, 63,
   64, 65,
   66, 66,
   60, 67
};

#define animDFlyRt_Width   (2)
#define animDFlyRt_Height  (6)

const char animDFlyRt[2 * 6] PROGMEM=
{
   68, 69,
   70, 71,
   72, 73,
   74, 75,
   66, 66,
   76, 71
};

#define animTurtleLt_Width   (2)
#define animTurtleLt_Height  (3)

const char animTurtleLt[2 * 3] PROGMEM=
{
   77, 78,
   79, 80,
   81, 82
};

#define animTurtleRt_Width   (2)
#define animTurtleRt_Height  (3)

const char animTurtleRt[2 * 3] PROGMEM=
{
   83, 84,
   85, 86,
   87, 88
};

#define animSnailLt_Width   (1)
#define animSnailLt_Height  (1)

const char animSnailLt[1 * 1] PROGMEM=
{
   89
};

#define animSnailRt_Width   (1)
#define animSnailRt_Height  (1)

const char animSnailRt[1 * 1] PROGMEM=
{
   90
};