
const char animLynxIdleLt[3 * 2] PROGMEM={
    0,  1,  2,
    3,  4,  5
};

const char animLynxIdleRt[3 * 2] PROGMEM={
    6,  7,  8,
    9, 10, 11
};

const char animLynxRunLt[3 * 12] PROGMEM={
    0, 12, 13,
   14, 15, 16,
    0,  1,  2,
   17, 18, 19,
   20, 21, 22,
   23, 24, 25,
    0, 26, 27,
   28, 29, 30,
    0, 31, 32,
   33, 34, 35,
    0, 36, 37,
   38, 39, 40
};

const char animLynxRunRt[3 * 12] PROGMEM={
   41, 42,  8,
   43, 44, 45,
    6,  7,  8,
   46, 47, 48,
   49, 50, 51,
   52, 53, 54,
   55, 56,  8,
   57, 58, 59,
   60, 61,  8,
   62, 63, 64,
   65, 66,  8,
   67, 68, 69
};

const char animDFlyLt[2 * 8] PROGMEM={
   70, 71,
   72, 73,
   74, 75,
   76, 77,
   78, 79,
   80, 81,
   71, 71,
   82, 83
};

const char animDFlyRt[2 * 8] PROGMEM={
   71, 84,
   85, 86,
   87, 88,
   89, 90,
   91, 92,
   93, 94,
   71, 71,
   95, 96
};

const char animTurtleIdleLt[2 * 1] PROGMEM={
   97, 98
};

const char animTurtleLt[2 * 3] PROGMEM={
   97, 98,
   99,100,
  101,102
};

const char animTurtleRt[2 * 3] PROGMEM={
  103,104,
  105,106,
  107,108
};
