
#define animLynxIdleRt_Width   (3)
#define animLynxIdleRt_Height  (2)

const char animLynxIdleRt[3 * 2] PROGMEM=
{
    1,  2,  3,
    4,  5,  6
};

#define animLynxIdleLt_Width   (3)
#define animLynxIdleLt_Height  (2)

const char animLynxIdleLt[3 * 2] PROGMEM=
{
    7,  8,  9,
   10, 11, 12
};

#define animLynxRunRt_Width   (3)
#define animLynxRunRt_Height  (12)

const char animLynxRunRt[3 * 12] PROGMEM=
{
    1,  2, 13,
   14, 15, 16,
    1,  2, 13,
   17, 18, 19,
   20,  2, 21,
   22, 23, 24,
   25, 26,  3,
   27, 28, 29,
   30, 31,  3,
   32, 33, 34,
   35,  2,  3,
   36, 37, 38
};

#define animLynxRunLt_Width   (3)
#define animLynxRunLt_Height  (12)

const char animLynxRunLt[3 * 12] PROGMEM=
{
   39,  8,  9,
   40, 41, 42,
   39,  8,  9,
   43, 44, 45,
   46,  8, 47,
   48, 49, 50,
    7, 51, 52,
   53, 54, 55,
    7, 56, 57,
   58, 59, 60,
    7,  8, 61,
   62, 63, 64
};

#define animDFlyRt_Width   (2)
#define animDFlyRt_Height  (6)

const char animDFlyRt[2 * 6] PROGMEM=
{
   65, 66,
   67, 68,
   69, 70,
   71, 72,
    0,  0,
   73, 68
};

#define animDFlyLt_Width   (2)
#define animDFlyLt_Height  (6)

const char animDFlyLt[2 * 6] PROGMEM=
{
   74, 75,
   76, 77,
   78, 79,
   80, 81,
    0,  0,
   76, 82
};

#define animTurtleRt_Width   (2)
#define animTurtleRt_Height  (3)

const char animTurtleRt[2 * 3] PROGMEM=
{
   83, 84,
   85, 86,
   87, 88
};

#define animTurtleLt_Width   (2)
#define animTurtleLt_Height  (3)

const char animTurtleLt[2 * 3] PROGMEM=
{
   89, 90,
   91, 92,
   93, 94
};

#define animSnailRt_Width   (1)
#define animSnailRt_Height  (1)

const char animSnailRt[1 * 1] PROGMEM=
{
   95
};

#define animSnailLt_Width   (1)
#define animSnailLt_Height  (1)

const char animSnailLt[1 * 1] PROGMEM=
{
   96
};
