
#define mapBackground_Width   (30)
#define mapBackground_Height  (28)

const char mapBackground[30 * 28 + 2] PROGMEM=
{mapBackground_Width,mapBackground_Height,
    1,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  5,  6,  7,  8,  9, 10,  3,
    3,  3,  3,  3,  3,  3,  3,  3,  3, 11, 12,
    1,  2,  3,  3,  3,  3,  3,  3, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
   24, 25,  3,  3, 26, 27,  3,  3,  3, 11, 12,
    1,  2,  3,  3,  3,  3,  3,  3, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
   39, 40,  3, 41, 42, 43,  3,  3,  3, 11, 12,
    1,  2,  3,  3,  3,  3,  3,  3,  3, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
   54, 55,  3, 56, 57, 58,  3,  3,  3, 11, 12,
    1,  2,  3,  3, 59, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
   60, 60, 60, 61, 62, 63, 64,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,130,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,131,132,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  3,  3, 11, 12,
    1,  2,131,135,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,136,137,138, 11, 12,
    1,  2,139,140,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,141,142,143, 11, 12,
  144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,
  154,155,163,164,165,166,167,168,169,170,171,
  172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,
  191,192,193,131,131,194,195,196,197,198,199,
  200,  0,201,202,203,204,205,206,207,131,131,208,209,210,131,131,211,212,213,
  214,215,216,217,218,219,220,221,222,  0,223,
  224,225,226,226,226,226,226,226,226,227,228,226,227,228,226,226,226,226,226,
  226,226,229,230,226,226,229,230,226,231,232,
    2,233,234,234,234,234,234,234,234,235,236,234,235,236,234,234,234,234,234,
  234,234,237,238,234,234,237,238,234,239, 11
};

#define mapMonsterGreen0_Width   (1)
#define mapMonsterGreen0_Height  (1)

const char mapMonsterGreen0[1 * 1 + 2] PROGMEM=
{mapMonsterGreen0_Width,mapMonsterGreen0_Height,
   88
};

#define mapMonsterGreen1_Width   (2)
#define mapMonsterGreen1_Height  (1)

const char mapMonsterGreen1[2 * 1 + 2] PROGMEM=
{mapMonsterGreen1_Width,mapMonsterGreen1_Height,
   90, 91
};

#define mapMonsterGreen2_Width   (1)
#define mapMonsterGreen2_Height  (2)

const char mapMonsterGreen2[1 * 2 + 2] PROGMEM=
{mapMonsterGreen2_Width,mapMonsterGreen2_Height,
   89,
   94
};

#define mapMonsterGreen3_Width   (2)
#define mapMonsterGreen3_Height  (2)

const char mapMonsterGreen3[2 * 2 + 2] PROGMEM=
{mapMonsterGreen3_Width,mapMonsterGreen3_Height,
   92, 93,
   95, 96
};

#define mapMonsterPink0_Width   (1)
#define mapMonsterPink0_Height  (1)

const char mapMonsterPink0[1 * 1 + 2] PROGMEM=
{mapMonsterPink0_Width,mapMonsterPink0_Height,
   97
};

#define mapMonsterPink1_Width   (2)
#define mapMonsterPink1_Height  (1)

const char mapMonsterPink1[2 * 1 + 2] PROGMEM=
{mapMonsterPink1_Width,mapMonsterPink1_Height,
   99,100
};

#define mapMonsterPink2_Width   (1)
#define mapMonsterPink2_Height  (2)

const char mapMonsterPink2[1 * 2 + 2] PROGMEM=
{mapMonsterPink2_Width,mapMonsterPink2_Height,
   98,
  103
};

#define mapMonsterPink3_Width   (2)
#define mapMonsterPink3_Height  (2)

const char mapMonsterPink3[2 * 2 + 2] PROGMEM=
{mapMonsterPink3_Width,mapMonsterPink3_Height,
  101,102,
  104,105
};

#define mapMonsterYellow0_Width   (1)
#define mapMonsterYellow0_Height  (1)

const char mapMonsterYellow0[1 * 1 + 2] PROGMEM=
{mapMonsterYellow0_Width,mapMonsterYellow0_Height,
  106
};

#define mapMonsterYellow1_Width   (2)
#define mapMonsterYellow1_Height  (1)

const char mapMonsterYellow1[2 * 1 + 2] PROGMEM=
{mapMonsterYellow1_Width,mapMonsterYellow1_Height,
  108,109
};

#define mapMonsterYellow2_Width   (1)
#define mapMonsterYellow2_Height  (2)

const char mapMonsterYellow2[1 * 2 + 2] PROGMEM=
{mapMonsterYellow2_Width,mapMonsterYellow2_Height,
  107,
  112
};

#define mapMonsterYellow3_Width   (2)
#define mapMonsterYellow3_Height  (2)

const char mapMonsterYellow3[2 * 2 + 2] PROGMEM=
{mapMonsterYellow3_Width,mapMonsterYellow3_Height,
  110,111,
  113,114
};

#define mapMonsterDead0_Width   (1)
#define mapMonsterDead0_Height  (1)

const char mapMonsterDead0[1 * 1 + 2] PROGMEM=
{mapMonsterDead0_Width,mapMonsterDead0_Height,
  118
};

#define mapMonsterDead1_Width   (2)
#define mapMonsterDead1_Height  (1)

const char mapMonsterDead1[2 * 1 + 2] PROGMEM=
{mapMonsterDead1_Width,mapMonsterDead1_Height,
  120,121
};

#define mapMonsterDead2_Width   (1)
#define mapMonsterDead2_Height  (2)

const char mapMonsterDead2[1 * 2 + 2] PROGMEM=
{mapMonsterDead2_Width,mapMonsterDead2_Height,
  119,
  127
};

#define mapMonsterDead3_Width   (2)
#define mapMonsterDead3_Height  (2)

const char mapMonsterDead3[2 * 2 + 2] PROGMEM=
{mapMonsterDead3_Width,mapMonsterDead3_Height,
  122,123,
  128,129
};

#define mapShelter_Width   (3)
#define mapShelter_Height  (2)

const char mapShelter[3 * 2 + 2] PROGMEM=
{mapShelter_Width,mapShelter_Height,
  115,116,117,
  116,  0,116
};

#define mapShelterDmg0_Width   (1)
#define mapShelterDmg0_Height  (1)

const char mapShelterDmg0[1 * 1 + 2] PROGMEM=
{mapShelterDmg0_Width,mapShelterDmg0_Height,
  124
};

#define mapShelterDmg1_Width   (1)
#define mapShelterDmg1_Height  (1)

const char mapShelterDmg1[1 * 1 + 2] PROGMEM=
{mapShelterDmg1_Width,mapShelterDmg1_Height,
  125
};

#define mapShelterDmg2_Width   (1)
#define mapShelterDmg2_Height  (1)

const char mapShelterDmg2[1 * 1 + 2] PROGMEM=
{mapShelterDmg2_Width,mapShelterDmg2_Height,
  126
};

#define mapShelterDmg3_Width   (1)
#define mapShelterDmg3_Height  (1)

const char mapShelterDmg3[1 * 1 + 2] PROGMEM=
{mapShelterDmg3_Width,mapShelterDmg3_Height,
  0
};

#define mapNumerals_Width   (10)
#define mapNumerals_Height  (1)

const char mapNumerals[10 * 1 + 2] PROGMEM=
{mapNumerals_Width,mapNumerals_Height,
   67, 68, 69, 70, 71, 72, 73, 74, 75, 76
};

#define mapGameOver_Width   (9)
#define mapGameOver_Height  (1)

const char mapGameOver[9 * 1 + 2] PROGMEM=
{mapGameOver_Width,mapGameOver_Height,
   79, 80, 81, 82,  0, 83, 84, 82, 85
};

#define mapPressStart_Width   (11)
#define mapPressStart_Height  (1)

const char mapPressStart[11 * 1 + 2] PROGMEM=
{mapPressStart_Width,mapPressStart_Height,
   66, 85, 82, 86, 86,  0, 86, 87, 80, 85, 87
};

#define map1Up_Width   (3)
#define map1Up_Height  (1)

const char map1Up[3 * 1 + 2] PROGMEM=
{map1Up_Width,map1Up_Height,
   68, 65, 66
};

#define mapHi_Width   (2)
#define mapHi_Height  (1)

const char mapHi[2 * 1 + 2] PROGMEM=
{mapHi_Width,mapHi_Height,
   77, 78
};

#define mapLives_Width   (2)
#define mapLives_Height  (1)

const char mapLives[2 * 1 + 2] PROGMEM=
{mapLives_Width,mapLives_Height,
  133,134
};
