
#define mapEmuzeLogo_Width   (3)
#define mapEmuzeLogo_Height  (3)

const int mapEmuzeLogo[3 * 3 + 2] PROGMEM=
{mapEmuzeLogo_Width,mapEmuzeLogo_Height,
    0,  9,  0,
   10, 11, 12,
   13, 14, 15
};

#define mapKernelIcon_Width   (3)
#define mapKernelIcon_Height  (2)

const int mapKernelIcon[3 * 2 + 2] PROGMEM=
{mapKernelIcon_Width,mapKernelIcon_Height,
   20, 21, 22,
   23, 24, 25
};

#define mapMegatrisIcon_Width   (3)
#define mapMegatrisIcon_Height  (2)

const int mapMegatrisIcon[3 * 2 + 2] PROGMEM=
{mapMegatrisIcon_Width,mapMegatrisIcon_Height,
    0, 26,  0,
   26, 26, 26
};

#define mapWhackAMoleIcon_Width   (3)
#define mapWhackAMoleIcon_Height  (2)

const int mapWhackAMoleIcon[3 * 2 + 2] PROGMEM=
{mapWhackAMoleIcon_Width,mapWhackAMoleIcon_Height,
   27, 28, 29,
   30, 31, 32
};

#define mapVoidFighterIcon_Width   (3)
#define mapVoidFighterIcon_Height  (2)

const int mapVoidFighterIcon[3 * 2 + 2] PROGMEM=
{mapVoidFighterIcon_Width,mapVoidFighterIcon_Height,
   33, 34, 35,
   36, 37, 38
};

#define mapPongIcon_Width   (3)
#define mapPongIcon_Height  (2)

const int mapPongIcon[3 * 2 + 2] PROGMEM=
{mapPongIcon_Width,mapPongIcon_Height,
   39, 40, 41,
   42,  0, 43
};

#define mapArkanoidIcon_Width   (3)
#define mapArkanoidIcon_Height  (2)

const int mapArkanoidIcon[3 * 2 + 2] PROGMEM=
{mapArkanoidIcon_Width,mapArkanoidIcon_Height,
   44, 45, 46,
   47, 48, 49
};

#define mapUnknownIcon_Width   (3)
#define mapUnknownIcon_Height  (2)

const int mapUnknownIcon[3 * 2 + 2] PROGMEM=
{mapUnknownIcon_Width,mapUnknownIcon_Height,
   50, 51, 52,
   53, 54, 55
};

#define mapSpaceInvadersIcon_Width   (3)
#define mapSpaceInvadersIcon_Height  (2)

const int mapSpaceInvadersIcon[3 * 2 + 2] PROGMEM=
{mapSpaceInvadersIcon_Width,mapSpaceInvadersIcon_Height,
   56, 57, 58,
   59, 60, 61
};

#define mapPacmanIcon_Width   (3)
#define mapPacmanIcon_Height  (2)

const int mapPacmanIcon[3 * 2 + 2] PROGMEM=
{mapPacmanIcon_Width,mapPacmanIcon_Height,
   62, 63, 64,
   65, 66, 67
};

#define mapBcDashIcon_Width   (3)
#define mapBcDashIcon_Height  (2)

const int mapBcDashIcon[3 * 2 + 2] PROGMEM=
{mapBcDashIcon_Width,mapBcDashIcon_Height,
   68, 69, 70,
   71, 72, 73
};

#define mapAdvOfLolo_Width   (3)
#define mapAdvOfLolo_Height  (2)

const int mapAdvOfLolo[3 * 2 + 2] PROGMEM=
{mapAdvOfLolo_Width,mapAdvOfLolo_Height,
   74, 75, 76,
   77, 78, 79
};

#define mapZombienatorIcon_Width   (3)
#define mapZombienatorIcon_Height  (2)

const int mapZombienatorIcon[3 * 2 + 2] PROGMEM=
{mapZombienatorIcon_Width,mapZombienatorIcon_Height,
   80, 81, 82,
    0, 83,  0
};
