
#define mapEmuzeLogo_Width   (3)
#define mapEmuzeLogo_Height  (3)

const int mapEmuzeLogo[3 * 3 + 2] PROGMEM=
{mapEmuzeLogo_Width,mapEmuzeLogo_Height,
    0,  9,  0,
   10, 11, 12,
   13, 14, 15
};

#define mapUnknown0_Width   (3)
#define mapUnknown0_Height  (2)

const int mapUnknown0[3 * 2 + 2] PROGMEM=
{mapUnknown0_Width,mapUnknown0_Height,
   20, 21, 22,
   23, 24, 25
};

#define mapUnknown1_Width   (3)
#define mapUnknown1_Height  (2)

const int mapUnknown1[3 * 2 + 2] PROGMEM=
{mapUnknown1_Width,mapUnknown1_Height,
   32, 33, 34,
   35, 36, 37
};

#define mapUnknown2_Width   (3)
#define mapUnknown2_Height  (2)

const int mapUnknown2[3 * 2 + 2] PROGMEM=
{mapUnknown2_Width,mapUnknown2_Height,
   26, 27, 28,
   29, 30, 31
};

#define mapMegatris0_Width   (3)
#define mapMegatris0_Height  (2)

const int mapMegatris0[3 * 2 + 2] PROGMEM=
{mapMegatris0_Width,mapMegatris0_Height,
    0, 50,  0,
   50, 50, 50
};

#define mapWhackAMole0_Width   (3)
#define mapWhackAMole0_Height  (2)

const int mapWhackAMole0[3 * 2 + 2] PROGMEM=
{mapWhackAMole0_Width,mapWhackAMole0_Height,
   51, 52, 53,
   54, 55, 56
};

#define mapVoidFighter0_Width   (3)
#define mapVoidFighter0_Height  (2)

const int mapVoidFighter0[3 * 2 + 2] PROGMEM=
{mapVoidFighter0_Width,mapVoidFighter0_Height,
   57, 58, 59,
   60, 61, 62
};

#define mapPong0_Width   (3)
#define mapPong0_Height  (2)

const int mapPong0[3 * 2 + 2] PROGMEM=
{mapPong0_Width,mapPong0_Height,
   63, 64, 65,
   66,  0, 67
};

#define mapPong1_Width   (3)
#define mapPong1_Height  (2)

const int mapPong1[3 * 2 + 2] PROGMEM=
{mapPong1_Width,mapPong1_Height,
   68, 69, 70,
   71, 72, 73
};

#define mapPong2_Width   (3)
#define mapPong2_Height  (2)

const int mapPong2[3 * 2 + 2] PROGMEM=
{mapPong2_Width,mapPong2_Height,
    0,  0, 65,
   74, 75, 67
};

#define mapPong3_Width   (3)
#define mapPong3_Height  (2)

const int mapPong3[3 * 2 + 2] PROGMEM=
{mapPong3_Width,mapPong3_Height,
    0,  0, 76,
   74, 77, 78
};

#define mapPong4_Width   (3)
#define mapPong4_Height  (2)

const int mapPong4[3 * 2 + 2] PROGMEM=
{mapPong4_Width,mapPong4_Height,
   79,  0, 76,
   80, 81, 78
};

#define mapArkanoid0_Width   (3)
#define mapArkanoid0_Height  (2)

const int mapArkanoid0[3 * 2 + 2] PROGMEM=
{mapArkanoid0_Width,mapArkanoid0_Height,
   82, 83, 84,
   85, 86, 87
};

#define mapArkanoid1_Width   (3)
#define mapArkanoid1_Height  (2)

const int mapArkanoid1[3 * 2 + 2] PROGMEM=
{mapArkanoid1_Width,mapArkanoid1_Height,
   88, 89, 90,
   91, 92, 93
};

#define mapArkanoid2_Width   (3)
#define mapArkanoid2_Height  (2)

const int mapArkanoid2[3 * 2 + 2] PROGMEM=
{mapArkanoid2_Width,mapArkanoid2_Height,
   94, 95, 96,
   97, 98, 99
};

#define mapSpaceInvaders0_Width   (3)
#define mapSpaceInvaders0_Height  (2)

const int mapSpaceInvaders0[3 * 2 + 2] PROGMEM=
{mapSpaceInvaders0_Width,mapSpaceInvaders0_Height,
    0,100,101,
  102,103,104
};

#define mapSpaceInvaders1_Width   (3)
#define mapSpaceInvaders1_Height  (2)

const int mapSpaceInvaders1[3 * 2 + 2] PROGMEM=
{mapSpaceInvaders1_Width,mapSpaceInvaders1_Height,
  105,106,107,
  102,108,104
};

#define mapSpaceInvaders2_Width   (3)
#define mapSpaceInvaders2_Height  (2)

const int mapSpaceInvaders2[3 * 2 + 2] PROGMEM=
{mapSpaceInvaders2_Width,mapSpaceInvaders2_Height,
  109,110,  0,
  102,103,104
};

#define mapPacman0_Width   (3)
#define mapPacman0_Height  (2)

const int mapPacman0[3 * 2 + 2] PROGMEM=
{mapPacman0_Width,mapPacman0_Height,
  111,112,113,
  114,115,116
};

#define mapPacman1_Width   (3)
#define mapPacman1_Height  (2)

const int mapPacman1[3 * 2 + 2] PROGMEM=
{mapPacman1_Width,mapPacman1_Height,
  117,118,119,
  120,121,122
};

#define mapPacman2_Width   (3)
#define mapPacman2_Height  (2)

const int mapPacman2[3 * 2 + 2] PROGMEM=
{mapPacman2_Width,mapPacman2_Height,
  111,123,124,
  114,125,126
};

#define mapBcDash0_Width   (3)
#define mapBcDash0_Height  (2)

const int mapBcDash0[3 * 2 + 2] PROGMEM=
{mapBcDash0_Width,mapBcDash0_Height,
  127,128,129,
  130,131,132
};

#define mapBcDash1_Width   (3)
#define mapBcDash1_Height  (2)

const int mapBcDash1[3 * 2 + 2] PROGMEM=
{mapBcDash1_Width,mapBcDash1_Height,
  133,134,  0,
  135,136,137
};

#define mapBcDash2_Width   (3)
#define mapBcDash2_Height  (2)

const int mapBcDash2[3 * 2 + 2] PROGMEM=
{mapBcDash2_Width,mapBcDash2_Height,
    0,  0,  0,
  138,139,137
};

#define mapAdvOfLolo0_Width   (3)
#define mapAdvOfLolo0_Height  (2)

const int mapAdvOfLolo0[3 * 2 + 2] PROGMEM=
{mapAdvOfLolo0_Width,mapAdvOfLolo0_Height,
  140,141,142,
  143,144,145
};

#define mapAdvOfLolo1_Width   (3)
#define mapAdvOfLolo1_Height  (2)

const int mapAdvOfLolo1[3 * 2 + 2] PROGMEM=
{mapAdvOfLolo1_Width,mapAdvOfLolo1_Height,
  146,147,148,
  149,150,151
};

#define mapZombienator0_Width   (3)
#define mapZombienator0_Height  (2)

const int mapZombienator0[3 * 2 + 2] PROGMEM=
{mapZombienator0_Width,mapZombienator0_Height,
  152,153,154,
  155,156,157
};

#define mapZombienator1_Width   (3)
#define mapZombienator1_Height  (2)

const int mapZombienator1[3 * 2 + 2] PROGMEM=
{mapZombienator1_Width,mapZombienator1_Height,
  152,153,154,
  155,158,157
};

#define mapKernel0_Width   (3)
#define mapKernel0_Height  (2)

const int mapKernel0[3 * 2 + 2] PROGMEM=
{mapKernel0_Width,mapKernel0_Height,
   38, 39, 40,
   41, 42, 43
};
