
#define mapEgg_Width   (1)
#define mapEgg_Height  (1)

const char mapEgg[1 * 1 + 2] PROGMEM =
{mapEgg_Width,mapEgg_Height,
    26
};

#define mapIcicle_Width   (1)
#define mapIcicle_Height  (1)

const char mapIcicle[1 * 1 + 2] PROGMEM =
{mapIcicle_Width,mapIcicle_Height,
    14
};

#define mapStar_Width   (1)
#define mapStar_Height  (1)

const char mapStar[1 * 1 + 2] PROGMEM=
{mapStar_Width,mapStar_Height,
    2
};

#define mapLogBridge_Width   (1)
#define mapLogBridge_Height  (2)

const char mapLogBridge[1 * 2 + 2] PROGMEM=
{mapLogBridge_Width,mapLogBridge_Height,
    5,
    19
};

#define mapGndMid0_Width   (2)
#define mapGndMid0_Height  (2)

const char mapGndMid0[2 * 2 + 2] PROGMEM=
{mapGndMid0_Width,mapGndMid0_Height,
    6,  7,
   20, 21
};

#define mapGndMid1_Width   (2)
#define mapGndMid1_Height  (2)

const char mapGndMid1[2 * 2 + 2] PROGMEM=
{mapGndMid1_Width,mapGndMid1_Height,
   20, 21,
    6,  7
};

#define mapGndMid2_Width   (2)
#define mapGndMid2_Height  (2)

const char mapGndMid2[2 * 2 + 2] PROGMEM=
{mapGndMid2_Width,mapGndMid2_Height,
    7,  6,
   21, 20
};

#define mapGndMid3_Width   (2)
#define mapGndMid3_Height  (2)

const char mapGndMid3[2 * 2 + 2] PROGMEM=
{mapGndMid3_Width,mapGndMid3_Height,
   21, 20,
    7,  6
};

#define mapGrassLt_Width   (1)
#define mapGrassLt_Height  (2)

const char mapGrassLt[1 * 2 + 2] PROGMEM=
{mapGrassLt_Width,mapGrassLt_Height,
    8,
   22
};

#define mapGrassRt_Width   (1)
#define mapGrassRt_Height  (2)

const char mapGrassRt[1 * 2 + 2] PROGMEM=
{mapGrassRt_Width,mapGrassRt_Height,
    9,
   23
};

#define mapGrassMid_Width   (2)
#define mapGrassMid_Height  (1)

const char mapGrassMid[2 * 1 + 2] PROGMEM=
{mapGrassMid_Width,mapGrassMid_Height,
   10, 11
};

#define mapGndBtm_Width   (2)
#define mapGndBtm_Height  (1)

const char mapGndBtm[2 * 1 + 2] PROGMEM=
{mapGndBtm_Width,mapGndBtm_Height,
   12, 13
};

#define mapGndBtmLt_Width   (1)
#define mapGndBtmLt_Height  (2)

const char mapGndBtmLt[1 * 2 + 2] PROGMEM=
{mapGndBtmLt_Width,mapGndBtmLt_Height,
   24,
   22
};

#define mapGndBtmRt_Width   (1)
#define mapGndBtmRt_Height  (2)

const char mapGndBtmRt[1 * 2 + 2] PROGMEM=
{mapGndBtmRt_Width,mapGndBtmRt_Height,
   25,
   23
};

#define mapGndBtmGrp0_Width   (2)
#define mapGndBtmGrp0_Height  (2)

const char mapGndBtmGrp0[2 * 2 + 2] PROGMEM=
{mapGndBtmGrp0_Width,mapGndBtmGrp0_Height,
    6,  7,
   12, 13
};

#define mapGndBtmGrp1_Width   (2)
#define mapGndBtmGrp1_Height  (2)

const char mapGndBtmGrp1[2 * 2 + 2] PROGMEM=
{mapGndBtmGrp1_Width,mapGndBtmGrp1_Height,
   20, 21,
   12, 13
};

#define mapGndBtmGrp2_Width   (2)
#define mapGndBtmGrp2_Height  (2)

const char mapGndBtmGrp2[2 * 2 + 2] PROGMEM=
{mapGndBtmGrp2_Width,mapGndBtmGrp2_Height,
    7,  6,
   12, 13
};

#define mapGndBtmGrp3_Width   (2)
#define mapGndBtmGrp3_Height  (2)

const char mapGndBtmGrp3[2 * 2 + 2] PROGMEM=
{mapGndBtmGrp3_Width,mapGndBtmGrp3_Height,
   21, 20,
   12, 13
};

#define mapIce_Width   (1)
#define mapIce_Height  (1)

const char mapIce[1 * 1 + 2] PROGMEM=
{mapIce_Width,mapIce_Height,
   15
};

#define mapTimeBest_Width   (1)
#define mapTimeBest_Height  (1)

const char mapTimeBest[1 * 1 + 2] PROGMEM=
{mapTimeBest_Width,mapTimeBest_Height,
   16
};

#define mapPlant_Width   (2)
#define mapPlant_Height  (1)

const char mapPlant[2 * 1 + 2] PROGMEM=
{mapPlant_Width,mapPlant_Height,
   17, 18
};

#define mapPupLedge_Width   (2)
#define mapPupLedge_Height  (1)

const char mapPupLedge[2 * 1 + 2] PROGMEM=
{mapPupLedge_Width,mapPupLedge_Height,
   107, 108
};

#define mapGndPlat_Width   (4)
#define mapGndPlat_Height  (2)

const char mapGndPlat[4 * 2 + 2] PROGMEM=
{mapGndPlat_Width,mapGndPlat_Height,
    8, 10, 11,  9,
   22, 12, 13, 23
};

#define mapPupEgg_Width   (1)
#define mapPupEgg_Height  (1)

const char mapPupEgg[1 * 1 + 2] PROGMEM=
{mapPupEgg_Width,mapPupEgg_Height,
   26
};

#define mapPupEggWater_Width   (1)
#define mapPupEggWater_Height  (1)

const char mapPupEggWater[1 * 1 + 2] PROGMEM=
{mapPupEggWater_Width,mapPupEggWater_Height,
   27
};

#define mapHourGlass_Width   (2)
#define mapHourGlass_Height  (2)

const char mapHourGlass[2 * 2 + 2] PROGMEM=
{mapHourGlass_Width,mapHourGlass_Height,
   28, 29,
   42, 43
};

#define mapBoots_Width   (2)
#define mapBoots_Height  (1)

const char mapBoots[2 * 1 + 2] PROGMEM=
{mapBoots_Width,mapBoots_Height,
   30, 31
};

#define mapBootsWater_Width   (2)
#define mapBootsWater_Height  (1)

const char mapBootsWater[2 * 1 + 2] PROGMEM=
{mapBootsWater_Width,mapBootsWater_Height,
   44, 45
};

#define mapPsn_Width   (2)
#define mapPsn_Height  (2)

const char mapPsn[2 * 2 + 2] PROGMEM=
{mapPsn_Width,mapPsn_Height,
   32, 33,
   46, 47
};

#define mapPsnWater_Width   (2)
#define mapPsnWater_Height  (2)

const char mapPsnWater[2 * 2 + 2] PROGMEM=
{mapPsnWater_Width,mapPsnWater_Height,
   34, 35,
   48, 49
};

#define mapBomb_Width   (2)
#define mapBomb_Height  (2)

const char mapBomb[2 * 2 + 2] PROGMEM=
{mapBomb_Width,mapBomb_Height,
   36, 37,
   50, 51
};

#define mapBuddha_Width   (2)
#define mapBuddha_Height  (2)

const char mapBuddha[2 * 2 + 2] PROGMEM=
{mapBuddha_Width,mapBuddha_Height,
   38, 39,
   52, 53
};

#define mapFlower_Width   (2)
#define mapFlower_Height  (2)

const char mapFlower[2 * 2 + 2] PROGMEM=
{mapFlower_Width,mapFlower_Height,
   40, 41,
   54, 55
};

#define mapPogo_Width   (1)
#define mapPogo_Height  (2)

const char mapPogo[1 * 2 + 2] PROGMEM=
{mapPogo_Width,mapPogo_Height,
   64,
   78
};

#define mapCloud_Width   (3)
#define mapCloud_Height  (2)

const char mapCloud[3 * 2 + 2] PROGMEM=
{mapCloud_Width,mapCloud_Height,
   65, 66, 67,
   79, 80, 81
};

#define mapIceBtmLt_Width   (1)
#define mapIceBtmLt_Height  (2)

const char mapIceBtmLt[1 * 2 + 2] PROGMEM=
{mapIceBtmLt_Width,mapIceBtmLt_Height,
   68,
   82
};

#define mapIceBtmRt_Width   (1)
#define mapIceBtmRt_Height  (2)

const char mapIceBtmRt[1 * 2 + 2] PROGMEM=
{mapIceBtmRt_Width,mapIceBtmRt_Height,
   69,
   83
};

#define mapSnowLt_Width   (1)
#define mapSnowLt_Height  (2)

const char mapSnowLt[1 * 2 + 2] PROGMEM=
{mapSnowLt_Width,mapSnowLt_Height,
   84,
   90
};

#define mapSnowRt_Width   (1)
#define mapSnowRt_Height  (2)

const char mapSnowRt[1 * 2 + 2] PROGMEM=
{mapSnowRt_Width,mapSnowRt_Height,
   87,
   93
};

#define mapSnowMid_Width   (2)
#define mapSnowMid_Height  (1)

const char mapSnowMid[2 * 1 + 2] PROGMEM=
{mapSnowMid_Width,mapSnowMid_Height,
   85, 86
};

#define mapIceBtm_Width   (2)
#define mapIceBtm_Height  (1)

const char mapIceBtm[2 * 1 + 2] PROGMEM=
{mapIceBtm_Width,mapIceBtm_Height,
   91, 92
};

#define mapIceBtmGrp_Width   (2)
#define mapIceBtmGrp_Height  (2)

const char mapIceBtmGrp[2 * 2 + 2] PROGMEM=
{mapIceBtmGrp_Width,mapIceBtmGrp_Height,
   15, 15,
   91, 92
};

#define mapSnowPlat_Width   (4)
#define mapSnowPlat_Height  (2)

const char mapSnowPlat[4 * 2 + 2] PROGMEM=
{mapSnowPlat_Width,mapSnowPlat_Height,
   84, 85, 86, 87,
   90, 91, 92, 93
};

#define mapMoon_Width   (2)
#define mapMoon_Height  (2)

const char mapMoon[2 * 2 + 2] PROGMEM=
{mapMoon_Width,mapMoon_Height,
   88, 89,
   94, 95
};

#define mapMushroom_Width   (6)
#define mapMushroom_Height  (2)

const char mapMushroom[6 * 2 + 2] PROGMEM=
{mapMushroom_Width,mapMushroom_Height,
   99,100,101,102,103,104,
    0, 96, 97, 98,  0,  0
};

#define mapGndTopLtWater_Width   (1)
#define mapGndTopLtWater_Height  (2)

const char mapGndTopLtWater[1 * 2 + 2] PROGMEM=
{mapGndTopLtWater_Width,mapGndTopLtWater_Height,
  105,
  109
};

#define mapGndTopRtWater_Width   (1)
#define mapGndTopRtWater_Height  (2)

const char mapGndTopRtWater[1 * 2 + 2] PROGMEM=
{mapGndTopRtWater_Width,mapGndTopRtWater_Height,
  106,
  110
};

#define mapGndBtmLtWater_Width   (1)
#define mapGndBtmLtWater_Height  (2)

const char mapGndBtmLtWater[1 * 2 + 2] PROGMEM=
{mapGndBtmLtWater_Width,mapGndBtmLtWater_Height,
  107,
  111
};

#define mapGndBtmRtWater_Width   (1)
#define mapGndBtmRtWater_Height  (2)

const char mapGndBtmRtWater[1 * 2 + 2] PROGMEM=
{mapGndBtmRtWater_Width,mapGndBtmRtWater_Height,
  108,
  112
};

#define mapGndBtmWater_Width   (2)
#define mapGndBtmWater_Height  (1)

const char mapGndBtmWater[2 * 1 + 2] PROGMEM=
{mapGndBtmWater_Width,mapGndBtmWater_Height,
  113,114
};

#define mapGndConeTopWater_Width   (2)
#define mapGndConeTopWater_Height  (2)

const char mapGndConeTopWater[2 * 2 + 2] PROGMEM=
{mapGndConeTopWater_Width,mapGndConeTopWater_Height,
  105,106,
  109,110
};

#define mapGndConeBtmWater_Width   (2)
#define mapGndConeBtmWater_Height  (2)

const char mapGndConeBtmWater[2 * 2 + 2] PROGMEM=
{mapGndConeBtmWater_Width,mapGndConeBtmWater_Height,
  107,108,
  111,112
};

#define mapGndBtmWaterGrp0_Width   (2)
#define mapGndBtmWaterGrp0_Height  (2)

const char mapGndBtmWaterGrp0[2 * 2 + 2] PROGMEM=
{mapGndBtmWaterGrp0_Width,mapGndBtmWaterGrp0_Height,
    6,  7,
  113,114
};

#define mapGndBtmWaterGrp1_Width   (2)
#define mapGndBtmWaterGrp1_Height  (2)

const char mapGndBtmWaterGrp1[2 * 2 + 2] PROGMEM=
{mapGndBtmWaterGrp1_Width,mapGndBtmWaterGrp1_Height,
   20, 21,
  113,114
};

#define mapGndBtmWaterGrp2_Width   (2)
#define mapGndBtmWaterGrp2_Height  (2)

const char mapGndBtmWaterGrp2[2 * 2 + 2] PROGMEM=
{mapGndBtmWaterGrp2_Width,mapGndBtmWaterGrp2_Height,
    7,  6,
  113,114
};

#define mapGndBtmWaterGrp3_Width   (2)
#define mapGndBtmWaterGrp3_Height  (2)

const char mapGndBtmWaterGrp3[2 * 2 + 2] PROGMEM=
{mapGndBtmWaterGrp3_Width,mapGndBtmWaterGrp3_Height,
   21, 20,
  113,114
};

#define mapExplosion_Width   (3)
#define mapExplosion_Height  (3)

const char mapExplosion[3 * 3 + 2] PROGMEM=
{mapExplosion_Width,mapExplosion_Height,
  115,128,116,
  128,128,128,
  129,128,130
};

#define animCoins_Width   (2)
#define animCoins_Height  (8)

const char animCoins[2 * 8 + 2] PROGMEM=
{animCoins_Width,animCoins_Height,
   56, 57,
   70, 71,
   58, 59,
   72, 73,
   60, 61,
   74, 75,
   62, 63,
   76, 77
};

#define animWfallTop_Width   (2)
#define animWfallTop_Height  (4)

const char animWfallTop[2 * 4 + 2] PROGMEM=
{2,1,
  117,118,
  119,120,
  121,122,
  123,124
};

#define animWfallBtm_Width   (2)
#define animWfallBtm_Height  (16)

const char animWfallBtm[2 * 16 + 2] PROGMEM=
{2,4,
 131,132,
  125,126,
  139,140,
    1,  1,
  133,134,
  127,142,
  141,143,
    1,  1,
  135,136,
  125,126,
  139,140,
    1,  1,
  137,138,
  127,142,
  141,143,
    1,  1
};

#define animFire_Width   (2)
#define animFire_Height  (4)

const char animFire[2 * 4 + 2] PROGMEM=
{2,2,
  144,145,
  148,149,
  146,147,
  150,151
};

#define animWave_Width   (1)
#define animWave_Height  (4)

const char animWave[1 * 4 + 2] PROGMEM=
{1,1,
  152,
  153,
  154,
  153
};

#define mapGndWaterPikeDn_Width   (3)
#define mapGndWaterPikeDn_Height  (3)

const char mapGndWaterPikeDn[3 * 3 + 2] PROGMEM=
{mapGndWaterPikeDn_Width,mapGndWaterPikeDn_Height,
    6,  7,  6,
  107, 21,108,
  111,  7,112
};

#define mapGndWaterPikeUp_Width   (3)
#define mapGndWaterPikeUp_Height  (3)

const char mapGndWaterPikeUp[3 * 3 + 2] PROGMEM=
{mapGndWaterPikeUp_Width,mapGndWaterPikeUp_Height,
  105,  7,106,
  109, 21,110,
    6,  7,  6
};

#define mapDashD_Width   (4)
#define mapDashD_Height  (6)

const char mapDashD[4 * 6 + 2] PROGMEM=
{mapDashD_Width,mapDashD_Height,
   85, 86, 85,  0,
   15,  0,  0, 86,
   15,  0,  0, 15,
   15, 36, 37, 15,
   15, 50, 51, 92,
   92, 91, 92,  0
};

#define mapDashA_Width   (4)
#define mapDashA_Height  (6)

const char mapDashA[4 * 6 + 2] PROGMEM=
{mapDashA_Width,mapDashA_Height,
    0, 85, 86,  0,
   86,  0,  0, 85,
   15, 30, 31, 15,
   15, 15, 15, 15,
   15,  0,  0, 15,
   92,  0,  0, 91
};

#define mapDashS_Width   (4)
#define mapDashS_Height  (6)

const char mapDashS[4 * 6 + 2] PROGMEM=
{mapDashS_Width,mapDashS_Height,
    0, 85, 86, 78,
   92,  0,  0, 85,
    0, 92,  0,  0,
    0,  0, 92,  0,
   92,  3,  0, 92,
    0, 92, 91,  0
};

#define mapDashH_Width   (4)
#define mapDashH_Height  (6)

const char mapDashH[4 * 6 + 2] PROGMEM=
{mapDashH_Width,mapDashH_Height,
   85,  0,  0, 86,
   15, 32, 33, 15,
   15, 46, 47, 15,
   15, 85, 86, 15,
   15,  0,  0, 15,
   91,  0,  0, 92
};

#define mapBFront_Width   (2)
#define mapBFront_Height  (11)

const char mapBFront[2 * 11 + 2] PROGMEM=
{mapBFront_Width,mapBFront_Height,
    9,  0,
    6,  9,
   20, 21,
    6, 25,
   25,  0,
    0,  0,
    9,  0,
    6,  9,
   20, 21,
   20, 25,
   13, 23
};

#define mapNumerals_Width   (12)
#define mapNumerals_Height  (1)

const char mapNumerals[12 * 1 + 2] PROGMEM=
{mapNumerals_Width,mapNumerals_Height,
  155,156,157,158,159,160,161,162,163,164,165,166
};

#define mapFonts_Width   (26)
#define mapFonts_Height  (1)

const char mapFonts[26 * 1 + 2] PROGMEM=
{mapFonts_Width,mapFonts_Height,
  167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,
  186,187,188,189,190,191,192
};

#define animPressStart_Width   (14)
#define animPressStart_Height  (4)

const char animPressStart[14 * 4 + 2] PROGMEM=
{14,1,
  168,191,  0,182,167,187,178,  0,179,169,182,174,171,171,
  179,187,185,175,169,  0,168,191,  0,173,184,167,167,  0,
    0,  0,  0,  0,187,192,171,168,181,190,  0,  0,  0,  0,
    0,182,184,171,185,185,  0,  0,185,186,167,184,186,  0
};

#define mapDucats_Width   (6)
#define mapDucats_Height  (1)

const char mapDucats[6 * 1 + 2] PROGMEM=
{mapDucats_Width,mapDucats_Height,
  170,187,169,167,186,185
};

#define mapStitchInTime_Width   (11)
#define mapStitchInTime_Height  (1)

const char mapStitchInTime[11 * 1 + 2] PROGMEM=
{mapStitchInTime_Width,mapStitchInTime_Height,
  185,186,175,186,169,174,  0,175,180,  0,  3
};

#define mapSpeedy_Width   (6)
#define mapSpeedy_Height  (1)

const char mapSpeedy[6 * 1 + 2] PROGMEM=
{mapSpeedy_Width,mapSpeedy_Height,
  185,182,171,171,170,191
};

#define mapDfly_Width   (9)
#define mapDfly_Height  (1)

const char mapDfly[9 * 1 + 2] PROGMEM=
{mapDfly_Width,mapDfly_Height,
  170,184,167,173,181,180,172,178,191
};

#define mapFloat_Width   (5)
#define mapFloat_Height  (1)

const char mapFloat[5 * 1 + 2] PROGMEM=
{mapFloat_Width,mapFloat_Height,
  172,178,181,167,186
};

#define mapLeap_Width   (4)
#define mapLeap_Height  (1)

const char mapLeap[4 * 1 + 2] PROGMEM=
{mapLeap_Width,mapLeap_Height,
  178,171,167,182
};

#define mapKaboom_Width   (6)
#define mapKaboom_Height  (1)

const char mapKaboom[6 * 1 + 2] PROGMEM=
{mapKaboom_Width,mapKaboom_Height,
  177,167,168,181,181,179
};

#define mapPoison_Width   (6)
#define mapPoison_Height  (1)

const char mapPoison[6 * 1 + 2] PROGMEM=
{mapPoison_Width,mapPoison_Height,
  182,181,175,185,181,180
};

#define mapTimeFlies_Width   (7)
#define mapTimeFlies_Height  (1)

const char mapTimeFlies[7 * 1 + 2] PROGMEM=
{mapTimeFlies_Width,mapTimeFlies_Height,
    3,  0,172,178,175,171,185
};

const char* pgmMaps[] PROGMEM = {
	mapGrassLt,					// 0
	mapGrassMid,				// 1
	mapGrassRt,					// 2
	mapGndMid0,					// 3
	mapGndBtmLtWater,			// 4
	mapGndBtmRtWater,			// 5
	mapGndBtmWaterGrp2,			// 6
	mapMushroom,				// 7
	mapBomb,					// 8
	mapGndBtmWaterGrp0,			// 9
	mapPsnWater,				// 10
	mapPupLedge,				// 11
	mapBootsWater,				// 12
	mapGndBtmWater,				// 13
	mapLogBridge,				// 14
	mapGndBtmWaterGrp1,			// 15
	mapGndMid3,					// 16
	mapGndMid1,					// 17
	mapPogo,					// 18
	mapGndBtm,					// 19
	mapGndBtmGrp1,				// 20
	mapGndBtmRt,				// 21
	mapGndBtmLt,				// 22
	mapHourGlass,				// 23
	mapBuddha,					// 24
	mapGndMid2,					// 25
	mapBoots,					// 26
	mapGndBtmGrp0,				// 27
	mapGndTopLtWater,			// 28
	mapGndTopRtWater,			// 29
	mapGndWaterPikeDn,			// 30
	mapGndWaterPikeUp,			// 31
	mapPsn,						// 32
	mapGndBtmWaterGrp3,			// 33
	mapGndConeTopWater,			// 34
	mapGndConeBtmWater,			// 35
	mapSnowPlat,				// 36
	mapSnowLt,					// 37
	mapSnowRt,					// 38
	mapSnowMid,					// 39
	mapIceBtm,					// 40
	mapIceBtmLt,				// 41
	mapIceBtmRt,				// 42
	mapIceBtmGrp,				// 43
	mapGndPlat,					// 44
	mapDashD,					// 45
	mapDashA,					// 46
	mapDashS,					// 47
	mapDashH,					// 48
	mapGndBtmGrp2,				// 49
	mapBFront,					// 50
	mapGndBtmGrp3,				// 51
	mapStar,					// 52
	mapEgg,					// 53
	mapCloud,					// 54
	mapMoon,					// 55
	mapFlower,					// 56
	mapPlant,					// 57
	mapIcicle,					// 58
	mapDucats,					// 59
	mapStitchInTime,				// 60
	mapSpeedy,					// 61
	mapDfly,					// 62
	mapFloat,					// 63
	mapLeap,					// 64
	mapKaboom,				// 65
	mapPoison,					// 66
	mapTimeFlies				// 67
};
